name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches: main
      
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: vote-app
      
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ github.repository_owner }}/vote-app
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            
      # Checkout to the repo main branch
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # Set QEMU for multi-platform build
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0

      # All docker related command
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
