name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches: main

      
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: vote-app
    steps:
      # Checkout to the repo main branch
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # All docker related command
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ env.GH_REGISTRY }}/${{ github.repository_owner }}/vote-app:latest
        with:
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,max
